# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool: Custom-Pool
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docify'
        repository: 'server'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: 'server/'
    - task: Docker@2
      inputs:
        containerRegistry: 'docify'
        repository: 'client'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: 'client/'
    - task: Docker@2
      inputs:
        containerRegistry: 'docify'
        repository: 'auth'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        buildContext: 'auth/'
    
